#!/bin/sh
# vimspectr120-dark, a shell theme script by nightsense
# generated with a template adapted from
# Base16 Shell template by Chris Kempson (http://chriskempson.com)

# linux console
if [ "${TERM%%-*}" = 'linux' ]; then
  echo -e "\e]P00a1a0a"
  echo -e "\e]P19c564c"
  echo -e "\e]P2407547"
  echo -e "\e]P3a18e53"
  echo -e "\e]P4547385"
  echo -e "\e]P57f5f91"
  echo -e "\e]P64a7d76"
  echo -e "\e]P7709170"
  echo -e "\e]P84f734f"
  echo -e "\e]P99e6d50"
  echo -e "\e]PA173017"
  echo -e "\e]PB4f734f"
  echo -e "\e]PC709170"
  echo -e "\e]PDddebdd"
  echo -e "\e]PE996673"
  echo -e "\e]PFf5fff5"
  echo -e "\e[H"
  echo -e "\e[2J"
  exit 0
fi

color00="0a/1a/0a" # Base 00 - Black
color01="9c/56/4c" # Base 08 - Red
color02="40/75/47" # Base 0B - Green
color03="a1/8e/53" # Base 0A - Yellow
color04="54/73/85" # Base 0D - Blue
color05="7f/5f/91" # Base 0E - Magenta
color06="4a/7d/76" # Base 0C - Cyan
color07="70/91/70" # Base 05 - White
color08="4f/73/4f" # Base 03 - Bright Black
color09="9e/6d/50" # Base 09
color10="17/30/17" # Base 01
color11="4f/73/4f" # Base 02
color12="70/91/70" # Base 04
color13="dd/eb/dd" # Base 06
color14="99/66/73" # Base 0F
color15="f5/ff/f5" # Base 07 - Bright White
color_foreground="70/91/70" # Base 05
color_background="0a/1a/0a" # Base 00

if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  printf_template='\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\'
  printf_template_var='\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\'
  printf_template_custom='\033Ptmux;\033\033]%s%s\033\033\\\033\\'
elif [ "${TERM%%-*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  printf_template='\033P\033]4;%d;rgb:%s\033\\'
  printf_template_var='\033P\033]%d;rgb:%s\033\\'
  printf_template_custom='\033P\033]%s%s\033\\'
else
  printf_template='\033]4;%d;rgb:%s\033\\'
  printf_template_var='\033]%d;rgb:%s\033\\'
  printf_template_custom='\033]%s%s\033\\'
fi

# 16 color space
printf $printf_template 0  $color00
printf $printf_template 1  $color01
printf $printf_template 2  $color02
printf $printf_template 3  $color03
printf $printf_template 4  $color04
printf $printf_template 5  $color05
printf $printf_template 6  $color06
printf $printf_template 7  $color07
printf $printf_template 8  $color08
printf $printf_template 9  $color09
printf $printf_template 10 $color10
printf $printf_template 11 $color11
printf $printf_template 12 $color12
printf $printf_template 13 $color13
printf $printf_template 14 $color14
printf $printf_template 15 $color15

# foreground / background / cursor color
if [ -n "$ITERM_SESSION_ID" ]; then
  # iTerm2 proprietary escape codes
  printf $printf_template_custom Pg 709170 # foreground
  printf $printf_template_custom Ph 0a1a0a # background
  printf $printf_template_custom Pi 709170 # bold color
  printf $printf_template_custom Pj 4f734f # selection color
  printf $printf_template_custom Pk ddebdd # selected text color
  printf $printf_template_custom Pl  # cursor
  printf $printf_template_custom Pm 0a1a0a # cursor text
else
  printf $printf_template_var 10 $color_foreground
  printf $printf_template_var 11 $color_background
  if [ "${TERM%%-*}" = "rxvt" ]; then
    printf $printf_template_var 708 $color_background # internal border (rxvt)
  fi
  printf $printf_template_custom 12 ";7" # cursor (reverse video)
fi

# clean up
unset printf_template
unset printf_template_var
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color_foreground
unset color_background
